services:


  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - asa-network
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server

  asa-server:
    build:
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-network

  asa-server2:
    build:
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server2
    networks:
      - asa-network

  asa-server-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: asa-server-web
    networks:
      - asa-network

  asa-server-mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    container_name: asa-server-mail
    networks:
      - asa-network



networks:
  asa-network:
    driver: bridge